import { Inter } from "next/font/google";
import "./globals.css";
import CardHeader from "./components/shared/CardHeader";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const title = 'create-card';
  return (
    <html lang="en">
      <body className={inter.className}>
        <CardHeader title={title} />
        {children}

      </body>
    </html>
  );
}
